language: python
python:
- "3.5"
env:
- FLASK_ENV='testing'
- DB_HOST="localhost"
- DB_USERNAME="postgres"
- DB_NAME="store_manager"
services:
- postgresql
postgres:
  adapter: postrgresql
  database: store_manager_test
  username: postgres
install:
- pip install --upgrade pip
- pip install -r requirements.txt
before_script:
- psql -c 'create database store_manager_test;' -U postgres
script:
- python manage.py migrate
- python manage.py default_admin
- coverage run manage.py test
- codeclimate-test-reporter --token a898963a482dddbc2ec858ba38cf2e9df4da7c1f66cefcbf734cfe9645a18788